CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference_id VARCHAR(100) NOT NULL,
    billing_id VARCHAR(100) NOT NULL,
    merchant_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    fee_amount DECIMAL(10, 2) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    mdr_percentage DECIMAL(5, 2) NOT NULL,
    mdr_amount DECIMAL(10, 2) NOT NULL,
    payment_method ENUM('credit_card', 'debit_card', 'bank_transfer', 'ewallet') NOT NULL, 
    currency VARCHAR(3) NOT NULL,
    type ENUM('payment', 'refund') NOT NULL,
    issuer VARCHAR(50) NOT NULL,
    acquirer VARCHAR(50) NOT NULL,
    customer_mpan VARCHAR(100) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    settlement_date TIMESTAMP,
    status ENUM('pending', 'completed', 'settled', 'failed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE
);